### ISSUE TITLE
Copy Loop from ID creation

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/document-model-electron#295] opened 2024-05-13 16:01 UTC
From our conversation: 

**OZ:**
This could be happening because of the virtual item creation logic that's there right now where when you create a new item it first creates a virtual item. We do multiple different instances of creating IDs eventually so we essentially create an ID using uuid for the virtual item. And then when we confirm creation of the item we look for & we have a separate list of virtual items and then find that item by the uuid and then delete that one and then create a new one with a new ID and a couple of opportunities there for IDs to get mixed up because it is really the same field and we copy between the two objects. So I think that there is a chance that the bug could originate. 

**Wouter:**
The way to approach this is to write a unit test that reproduces the bug and then make sure that first of all it's blocked on the document model level, with the reducers, so that we don't allow the creation of duplicate IDs as a first step. And then once you have the test and the test is failing. If you then Implement that error, (and again as with all the errors of the reducers That doesn't mean that the whole thing needs to break if that happens, it means that we don't apply anything,) it results in an error instead of a state indication so once we have that covered, that should already prevent these duplicate items from being created. And then the next step is to also weed out the situations that lead to these duplicate IDs being used as input in the first place right. This is the kind of thing we can implement on the reducer levels since we know all of the id's.

**Comment by gpuente** [comment] 2024-05-15 20:30
Hello guys!! @acaldas @CallmeT-ty @froid1911 @ryanwolhuter

after a deep analysis of the issue with the duplicated nodes ID's I found the root cause of the problem.
please read the following document with the details: [conflict resolution issue.pdf](https://github.com/powerhouse-inc/document-model-electron/files/15326661/conflict.resolution.issue.pdf)

The main problem is the lack of information to determine if we are merging duplicated operations but at different indexes (conflict resolution).
We can't use the index information because an operation can be reshuffled if there's a conflict (merge conflict resolution)
And we can't use the hash, because if an operation is reshuffled, a new hash is generated (hash depends on the position of the operation in the operation history)

## Proposal Solution
A possible solution for this problem is to integrate a unique `id` in the `Operation` schema. This `id` can be generated when an **action** is dispatched and it should never be changed:

```json
{
    'id': 'my_unique_id',
    "hash": "hash-1",
    "timestamp": "2024-05-15T18:34:16.071Z",
    "input": {},
    "scope": "global",
    "type": "ACTION_TYPE",
    "index": 0,
    "skip": 0
}
```

this new `id` field can be used to identify duplicated operations that are positioned at different indexes when merging conflicted branches:

![Image](https://github.com/powerhouse-inc/document-model-electron/assets/20387722/b300607d-28fb-4df2-a3bc-105905d7694b)

### Important restrictions:

- The operation `id` can only be generated when the action is dispatched (client side only)
- A conflict resolution should never change the `id` of an operation
- Is possible to have 2 or more operations with the same `id` as long as they are exactly the same operation but with a different skip number:
```ts
const operationHistory = [
    { type: 'INCREMENT_1', index: 0, skip: 0, id: 1 },
    { type: 'INCREMENT_2', index: 1, skip: 0, id: 2 },
    { type: 'INCREMENT_3', index: 2, skip: 0, id: 3 },
    { type: 'UNDO', index: 3, skip: 1, id: 4 },
    { type: 'UNDO', index: 4, skip: 2, id: 4 },
    { type: 'UNDO', index: 5, skip: 3, id: 4 },
];
```

**Comment by acaldas** [comment] 2024-05-16 13:01
Sounds good to me!

**Comment by ryanwolhuter** [comment] 2024-05-16 14:04
@gpuente excellent work figuring this all out

**Comment by CallmeT-ty** [comment] 2024-05-28 09:22
@gpuente Great we were able to get to the bottom of this.👌
Is there any additional work as a result or could you give me a brief status on the issue's status? Ty!!

**Comment by gpuente** [comment] 2024-05-28 12:40
Already pushed the fix for this @CallmeT-ty. I need to merge a change into switchboard and after that update connect dependencies. I'll get this done by today and close this ticket after that 👍🏻

**Closed** 2024-05-28 14:00 UTC
